language: objective-c
xcode_project: BNet.xcodeproj # path to your xcodeproj folder
xcode_scheme: BNetTests
os: osx

# the following line is needed to enable the TravisCI build conditions
conditions: v1

stages:
  - name: Validations (SwiftLint)
    if: type != cron
  - name: Unit Tests
    if: type != cron

env:
  global:
    - SCHEME=BNetTests
    - PROJECT=BNet.xcodeproj
    - TEST_SDK=iphonesimulator13.6 
    - OS_11=11.4
    - OS_12=12.2
    - OS_13=13.0
  jobs: 
    - TEST_SDK=$TEST_SDK OS=$OS_11 NAME='iPhone 7'
    - TEST_SDK=$TEST_SDK OS=$OS_12 NAME='iPhone 8'
    - TEST_SDK=$TEST_SDK OS=$OS_13 NAME='iPhone 11'
    - TEST_SDK=$TEST_SDK OS=$OS_13 NAME='iPhone XR'


osx_image: xcode11.6

before_install:
  chmod +x scripts/unit_test.sh scripts/install_swiftlint.sh scripts/linter.sh

script: scripts/unit_test.sh -s $SCHEME -d "platform=iOS Simulator,name=$NAME,OS=$OS_11" -k $TEST_SDK -p $PROJECT

jobs:
  include:
    - stage: Validations (SwiftLint)
      install: scripts/install_swiftlint.sh
      script: scripts/linter.sh
      #after_success: ./upload_lint_report

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 53c300ec-047b-4367-8435-7a491b08f264

#notifications:
#  email:
#    on_failure: never