language: objective-c
xcode_project: BNet.xcodeproj # path to your xcodeproj folder
xcode_scheme: BNetTests
os: osx

# the following line is needed to enable the TravisCI build conditions
conditions: v1

matrix:
  include:
    - name: Unit Tests (XCode 11.6)
      osx_image: xcode11.6
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t 53c300ec-047b-4367-8435-7a491b08f264

    - name: Validations (SwiftLint)
      osx_image: xcode11.6
      install: scripts/install_swiftlint.sh
      script: scripts/linter.sh

before_install:
  chmod +x scripts/ci_test.sh scripts/install_swiftlint.sh scripts/linter.sh

env:
  global:
    - TEST_SDK=iphonesimulator13.6 OS=11.4 NAME='iPhone 7'
    - TEST_SDK=iphonesimulator13.6 OS=12.0 NAME='iPhone 8'
    - TEST_SDK=iphonesimulator13.6 OS=13.0 NAME='iPhone 11'
    - TEST_SDK=iphonesimulator13.6 OS=12.0 NAME='iPhone XR'

#notifications:
#  email:
#    on_failure: never